server:
  port: 8080

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: api-gateway
    prefer-ip-address: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user_service_basic
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /api/users/${segment}

        - id: user_service_fake
          uri: lb://user-service
          predicates:
            - Path=/api/fakeusers/**
          filters:
            - RewritePath=/api/fakeusers/(?<segment>.*), /api/fakeusers/${segment}

        - id: user_service_hateoas
          uri: lb://user-service
          predicates:
            - Path=/api/hateoasusers/**
          filters:
            - RewritePath=/api/hateoasusers/(?<segment>.*), /api/hateoasusers/${segment}

        - id: swagger-ui
          uri: lb://user-service
          predicates:
            - Path=/swagger-ui/**,/v3/api-docs/**,/swagger-ui.html
          filters:
            - RewritePath=/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
            - RewritePath=/v3/api-docs/(?<segment>.*), /v3/api-docs/${segment}